version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo
  build:
    commands:
      - echo
artifacts:
  files:
    - src/**/*
    - package.json